#pragma once

#include <stdint.h>
#include <stdlib.h>


#ifdef MBEDTLS_HAVE_ASM
#undef MBEDTLS_HAVE_ASM
#endif

#ifdef MBEDTLS_AESNI_C
#undef MBEDTLS_AESNI_C
#endif

#ifdef MBEDTLS_PADLOCK_C
#undef MBEDTLS_PADLOCK_C
#endif

#ifdef EMBEDDED
#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_TIMING_ALT
#define MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_AES_FEWER_TABLES
#endif




#define MBEDTLS_ENTROPY_FORCE_SHA256


#undef MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224R1_ENABLED
#define MBEDTLS_ECP_DP_SECP256R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP521R1_ENABLED
#undef MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef MBEDTLS_ECP_DP_SECP256K1_ENABLED
#undef MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef MBEDTLS_ECP_DP_CURVE448_ENABLED


#undef MBEDTLS_CIPHER_MODE_CBC
#undef MBEDTLS_CIPHER_MODE_CFB
#undef MBEDTLS_CIPHER_MODE_CTR
#undef MBEDTLS_CIPHER_MODE_OFB
#undef MBEDTLS_CIPHER_MODE_XTS

#undef MBEDTLS_CIPHER_PADDING_PKCS7
#undef MBEDTLS_CIPHER_PADDING_ONE_AND_ZEROS
#undef MBEDTLS_CIPHER_PADDING_ZEROS_AND_LEN
#undef MBEDTLS_CIPHER_PADDING_ZEROS


#undef MBEDTLS_ECDH_LEGACY_CONTEXT
#undef MBEDTLS_PK_PARSE_EC_EXTENDED
#undef MBEDTLS_FS_IO
#undef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C

// force 32 bit MPI implementation
#define MBEDTLS_HAVE_INT32



#define MBEDTLS_PLATFORM_MEMORY


#define MBEDTLS_PLATFORM_STD_CALLOC mbedtls_our_calloc
#define MBEDTLS_PLATFORM_STD_FREE mbedtls_our_free


void* MBEDTLS_PLATFORM_STD_CALLOC(size_t a, size_t b);
void MBEDTLS_PLATFORM_STD_FREE(void* pointer);